// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtH0s8Jtl_5tVswxFfREIhtbZmPe-ics',
    appId: '1:722313198637:web:a2addbe02a81f0938c8ca4',
    messagingSenderId: '722313198637',
    projectId: 'testeflutter-430ad',
    authDomain: 'testeflutter-430ad.firebaseapp.com',
    storageBucket: 'testeflutter-430ad.appspot.com',
    measurementId: 'G-6Z859JEMLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ3Z2JQtbBGkZjjCzxe1qtEJM6LovVZuI',
    appId: '1:722313198637:android:c3a8cd428571c00a8c8ca4',
    messagingSenderId: '722313198637',
    projectId: 'testeflutter-430ad',
    storageBucket: 'testeflutter-430ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD86VL7SO9gg7McElsoD28IPUthcpRHsM',
    appId: '1:722313198637:ios:827f982b534284848c8ca4',
    messagingSenderId: '722313198637',
    projectId: 'testeflutter-430ad',
    storageBucket: 'testeflutter-430ad.appspot.com',
    iosClientId:
        '722313198637-v8i3eu99r1tf5asjbas0m2irgoh8skjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cprvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD86VL7SO9gg7McElsoD28IPUthcpRHsM',
    appId: '1:722313198637:ios:827f982b534284848c8ca4',
    messagingSenderId: '722313198637',
    projectId: 'testeflutter-430ad',
    storageBucket: 'testeflutter-430ad.appspot.com',
    iosClientId:
        '722313198637-v8i3eu99r1tf5asjbas0m2irgoh8skjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cprvApp',
  );
}
