// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpn6R3pS5POWtKyS-UzfvuI0V2SKQQeg',
    appId: '1:458892423774:web:f2368fa80b1ef5e2037acf',
    messagingSenderId: '458892423774',
    projectId: 'teste-mac-16d00',
    authDomain: 'teste-mac-16d00.firebaseapp.com',
    storageBucket: 'teste-mac-16d00.appspot.com',
    measurementId: 'G-G7XMRZR9Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthEzcNQhcg3k3YYkIUz_JdRvbwBT-eL0',
    appId: '1:458892423774:android:d90d7abd33f09b8f037acf',
    messagingSenderId: '458892423774',
    projectId: 'teste-mac-16d00',
    storageBucket: 'teste-mac-16d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxR7MHQAIcef21YOsgIRfeUXOKWVRc18',
    appId: '1:458892423774:ios:542f5ad7240ab47f037acf',
    messagingSenderId: '458892423774',
    projectId: 'teste-mac-16d00',
    storageBucket: 'teste-mac-16d00.appspot.com',
    androidClientId: '458892423774-tp6816afcf69gps1j1tsbb3a2akdml4v.apps.googleusercontent.com',
    iosClientId: '458892423774-2aji96sm4fpo5efmpl9758a0sb09k96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.cprvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTxR7MHQAIcef21YOsgIRfeUXOKWVRc18',
    appId: '1:458892423774:ios:542f5ad7240ab47f037acf',
    messagingSenderId: '458892423774',
    projectId: 'teste-mac-16d00',
    storageBucket: 'teste-mac-16d00.appspot.com',
    androidClientId: '458892423774-tp6816afcf69gps1j1tsbb3a2akdml4v.apps.googleusercontent.com',
    iosClientId: '458892423774-2aji96sm4fpo5efmpl9758a0sb09k96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.cprvApp',
  );
}
